import { Link, Navigate, useLocation } from 'react-router-dom';
import { categories, navigation } from '../data/sunriseData';
import Seo from '../seo/Seo';

export default function NotFoundPage() {
  const { pathname } = useLocation();
  // Old-site URLs (e.g. /vacuum-tray-dryer.html) still work in development; production
  // serves static redirect files generated by scripts/prerender.mjs.
  const moved = navigation.legacyRedirects[pathname];
  if (moved) return <Navigate to={moved} replace />;

  return (
    <>
      <Seo title="Page not found" description="The page you are looking for does not exist." path={pathname} noindex />
      <section className="section">
        <div className="container" style={{ textAlign: 'center', maxWidth: 720 }}>
          <div className="eyebrow">Error 404</div>
          <h1>We couldn’t find that page</h1>
          <p className="lead">It may have moved when we redesigned our website. Try one of these instead:</p>
          <div className="btn-row" style={{ justifyContent: 'center', margin: '28px 0 40px' }}>
            <Link to="/" className="btn btn-dark">Home</Link>
            <Link to="/products" className="btn btn-primary">All products</Link>
            <Link to="/contact" className="btn btn-outline">Contact us</Link>
          </div>
          <div className="chip-list" style={{ justifyContent: 'center' }}>
            {categories.map((c) => <Link key={c.id} to={c.path} className="chip">{c.name}</Link>)}
          </div>
        </div>
      </section>
    </>
  );
}
